tyoing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls), #このルーティング設定はDjangoの管理サイト用
    path('',include('typing_app.urls')),
    path('accounts/',include('allauth.urls')),

]

typing_app/urls.py
from django.urls import path

from . import views

app_name='typing_app'
urlpatterns=[
    path('', views.IndexViews.as_view(), name="index"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),   
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    """認証ユーザーモデル"""

    class Meta:
        verbose_name_plural= 'CustomUser'

# Create your models here.

typing_app/models.py
from django.db import models

# Create your models here.

typing_app/forms.py
from django import forms

class InquiryForm(forms.Form):
    name=forms.CharField(label='氏名', max_length=30)
    email=forms.EmailField(label='メールアドレス')
    title=forms.EmailField(label='タイトル', max_length=30)
    message=forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

        self.fields['name'].widget.attrs['class']='form-control col-9'
        self.fields['name'].widget.attrs['placeholder']='お名前を入力してください'
        self.fields['email'].widget.attrs['class']='form-control col-11'
        self.fields['email'].widget.attrs['placeholder']='メールアドレスを記入してください'
        self.fields['title'].widget.attrs['class']='form-control col-11'
        self.fields['title'].widget.attrs['placeholder']='タイトルをここに入力してください'
        self.fields['message'].widget.attrs['class']='form-control col-12'
        self.fields['message'].widget.attrs['placeholder']='メッセージをここに入力してください'

accounts/views.py
from django.shortcuts import render

# Create your views here.

typing_app/views.py
from django.views import generic
from .forms import InquiryForm
from django.shortcuts import render


# Create your views here.
class IndexViews(generic.TemplateView):
    template_name='index.html'

class InquiryView(generic.FormView): #ここではデータベースを使用する機会がないのでFormViewクラスを継承
    template_name="inquiry.html"
    form_class=InquiryForm

def Typing(request):
    return render(request, 'typing_app/Typing.html')

typing_app/templates/base.html
<!DOCTYPE html>
{% load static %}


<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" context="">
        <meta name="author" context="">

        <title>{% block title %}{% endblock %}</title>

        <!-- Bootstrap core CSS -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Custom fonts for this template -->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i400,400i,700,700i,900,900i" rel="stylesheet">

        <!-- Custom styles for this template  -->
        <link href="{% static 'css/one-page-wonder.min.css' %}" rel="stylesheet">
        
        <!-- My style -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">

        <!--Itabashi-->
        <link rel="stylesheet" type="text/css" media="screen,print" href="{% static 'css/typing.css' %}" />
        {% block head %}{% endblock %}
    </head>

    <body>
        <div id="wrapper">
            <!-- Navigation -->
            <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'typing_app:index' %}">TYPING APPLICATION</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggle-icon"></span> 
                    </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item {% block active_inquiry %}{% endblock %}">
                                <a class="nav-link" href="{% url 'typing_app:inquiry' %}">INQUIRY</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav mr-auto">
                            {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                            </li>
                            {% else %}
                            <li class="nav-item {% block active_signup %}{% endblock %}">
                                <a class="nav-link" href="{% url 'account_signup' %}">Sing Up</a>
                            </li>
                            <li class="nav-item {% block active_login %}{% endblock %}">
                                <a class="nav-link" href="{% url 'account_login' %}">Log in</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>

            {% block header %}{% endblock %}

            {% block contents %}{% endblock %}

            <!-- Footer -->
            <footer class="py-5 bg-black">
                <div class="container">
                    <p class="m-0 text-center text-white" style="font-size: 0.7rem ;">Copyright &copy;TYPING_APP 2020</p>
                </div>
                <!-- /.container -->
            </footer>

            <!-- Bootstrap core JavaScript -->
            <script src="{% static 'vendor/jquery/jquery.min.js' %}"></Script>
                <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        </div>
    </body>

</html>

typing_app/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load static %}

{% block title %}己の限界に挑戦！|Typing app{% endblock %}

{% block header %}


<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container">
        <h1 class="masthead-heading mb-0">TYPING_APP</h1>
        <h2 class="masthead-subheading mb-0">TYPINGにチャレンジ</h2>
        <a  data-toggle="modal" data-target="#testModal" class="btn btn-primary btn-xl rounded-pill mt-5">PLAY NOW</a>
        <a href="{% url 'account_login' %}" class="btn btn-primary btn-xl rounded-pill mt-5">LOG IN</a>

        </div>
    </div>


    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>

   
</header>

<!-- ボタン・リンククリック後に表示される画面の内容 -->
 <div class="modal fade" id="testModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true" data-keyboard="true">
    <div class="modal-dialog modal-xl modal-dialog-centered" >
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="basicModal">TYPING!!</h4>
            </div>
            <div class="modal-body">
                <body onload="gameSet()" class="itabashi">
                    <div id="main_typing" class="itabashi">
                        <!-- 時間の表示 -->
                        <p id="time" class="itabashi">最初の一文字入力でスタート</p>
                
                        <div class="question itabashi" >
                            <!-- 出題 -->
                            <font id="mondai" class="itabashi"></font>
                        </div>
                        <!-- タイピング済みの部分の表示 -->
                        <p id="input" class="itabashi"></p>
                        <!-- ミスタイプ数の表示 -->
                        <p id="missType" class="itabashi"></p>
                
                        <button id="retry" type="button" onclick="location.reload()" class="itabashi">
                            リトライ
                        </button>
                
                    </div>
                
                  
                
                
                    <script type="text/javascript" src="{% static 'js/typing.js' %}"></script>
                </body>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
            </div>
        </div>
    </div>
 </div>


{% endblock %}





 

typing_app/templates/inquiry.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block title %}お問い合わせ|Typing_application{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="post">
                {% csrf_token %}

                {{ form.non_field_errors }}

                {% for field in form %}
                    <div class="from-group row">
                        <label for="{{ field.id_for_label }}" class="col-4 col-form-label">
                            <strong>{{ field.label_tag}}</strong>
                        </label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors}}
                        </div>
                    </div>
                {% endfor %}

                <div class="offset-sm-4 col-sm-8">
                    <button class="btn btn-primary" type="submit">送信</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

typing_app/templates/ranking.html
<!DOCTYPE html>
{% extends 'base.html '%}

{% block title %}ランキング|Typing_application{% endblock %}

{% block contents %}

typing_app/templates/typing_app/Typing.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="UTF-8" />
    <title>typingGame</title>
    <link rel="stylesheet" type="text/css" media="screen,print" href="{% static 'css/typing.css' %}" />
</head>


<body>
    <h2>タイピングゲーム</h2>
    <div id="frame"></div>
    <input type="button" class="button" id="restart" value="restart" onclick="gameSet()">
    <script type="text/javascript" src="{% static 'js/typing.js' %}"></script>
</body>

</html>